se agrega validación de tipo de archivo

diff --git a/package/files/executables/detector b/package/files/executables/detector
--- a/package/files/executables/detector
+++ b/package/files/executables/detector
@@ -49,11 +49,16 @@ function processFile() {
         rejectFile $1 "empty file"; return;
     fi
 
+    if ! [[ $(file $1) =~ ASCII ]]; then
+        info "processFile" "Invalid file: invalid type file - $name"
+        rejectFile $1 "invalid type"; return;
+    fi
+
     # validamos que el nombre no tenga espacios
     case "$name" in  
      *\ * )
         # echo "match"
-        echo "Invalid file name - $name"
+        # echo "Invalid file name - $name"
         info "processFile" "Invalid file: invalid file name - $name"
         rejectFile $1 "invalid file name"; return;
           ;;
@@ -64,7 +69,7 @@ function processFile() {
 
     # validacion de nombre
     if ! [[ $name =~ [^_]+-[^_]+-[^_]+-[^_] ]]; then
-        echo "Invalid file name - $name"
+        # echo "Invalid file name - $name"
         info "processFile" "Invalid file: invalid file name - $name"
         rejectFile $1 "invalid file name"; return;
     fi
@@ -93,13 +98,13 @@ function processFile() {
 
     # If the system is not present in the p-s.mae it's rejected.
     if [ "$exist" = "false" ]; then
-        echo "The current file is not present in the system's master table. - $name"
+        # echo "The current file is not present in the system's master table. - $name"
         info "processFile" "Invalid file: file is not present in the system's master table. - $name"
         rejectFile $1 "update rejected"; return;
     fi
 
     if [ "$year" -lt 2016 ]; then
-        echo "Invalid file: Year before 2016 - $name"
+        # echo "Invalid file: Year before 2016 - $name"
         info "processFile" "Invalid file: Year before 2016 - $name"
         rejectFile $1 "update rejected"; return;
     fi
@@ -107,7 +112,7 @@ function processFile() {
     # validacion de mes
     #echo "Month: " $month
     if [ "$month" -lt 1 ] || [ "$month" -gt 12 ]; then
-        echo "Invalid file: Invalid month - $name"
+        # echo "Invalid file: Invalid month - $name"
         info "processFile" "Invalid file: Invalid month - $name"
         rejectFile $1 "update rejected"; return;
     fi
@@ -115,12 +120,12 @@ function processFile() {
     # valicacion de periodo
     # todo: sacar harcodeo del periodo
     if [ "$year" -gt 2017 ] && [ "$month" -gt 05 ]; then
-        echo "Invalid file: Invalid period - $name"
+        # echo "Invalid file: Invalid period - $name"
         info "processFile" "Invalid file: Invalid period - $name"
         rejectFile $1 "update rejected"; return;
     fi
 
-    echo "Accepted file: $name"
+    # echo "Accepted file: $name"
     info "processFile" "Accepted file: $name"
     acceptFile $1
 }
